runtime: java
env: flex
#service: my-app-doce
runtime_config:
  jdk: openjdk8
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 3.75
  disk_size_gb: 10
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: '/var/lib/jetty/webapps/root/WEB-INF/classes/key.json'